### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by xhaeffer** [inxomnyaa/fireworks#12]
Theres no error in console, i try in game, its not working

**Comment by inxomnyaa** [comment]
Are you using ElytraBoost? I know that they are incompatible. Also, only pmmp is supported, spoons are not allowed/supported.

I'd either need the output of /plugins and /version so we can maybe figure out your issue

**Comment by xhaeffer** [comment]
I using the teaspoon plugin , and there it is elytra boost

#RipEng

**Comment by inxomnyaa** [comment]
Discontinue reason: Fireworks item overwritten by another plugin.
