### ISSUE TITLE
Console crashes with the crashdump while using fireworks

### ISSUE THREAD

**Issue by ghost** [inxomnyaa/fireworks#13]
Latest version of pmmp

Error: Declaration of xenialdan\fireworks\FakeDataPacket::putEntityMetadata(array $metadata) must be compatible with pocketmine\network\mcpe\NetworkBinaryStream::putEntityMetadata(array $metadata): void
File: fireworks-master/src/xenialdan/fireworks/FakeDataPacket
Line: 152
Type: E_COMPILE_ERROR

**Comment by inxomnyaa** [comment]
> Latest version of pmmp

Ye next time a /version if possibru.
Might fix soon. My server is not ready for the metadata changes yet. If you use the src, you can just add :void yourself to make it work for now

**Comment by Antisa14200** [comment]
Well yeah latest, currently #647 build from jenkins

Dana 23. sij 2018. 23:23 osoba "XenialDan" <notifications@github.com>
napisala je:

**Comment by Antisa14200** [comment]
I'm using pocketmine from source thats why I told you latest version

Dana 24. sij 2018. 08:53 osoba "Ante Dragobratović" <aroniarni73@gmail.com>
napisala je:
