### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlicanCopur** [inxomnyaa/fireworks#20]
DataPropertyManager -> setItem is not a function

**Comment by inxomnyaa** [comment]
![grafik](https://user-images.githubusercontent.com/8733998/64487199-abde0800-d237-11e9-933c-d01f78b763a2.png)
API 3.9

**Comment by AlicanCopur** [comment]
Please look 3.9.4 API.

**Comment by inxomnyaa** [comment]
> This release is a patch update and does not contain any breaking API changes versus 3.9.3.

> Fixed entity metadata types for 1.12. The SLOT type was removed and a COMPOUND_TAG type added. This change involves changes to internal API which may break plugins. See the warning at the top of this changelog about API versioning.

Ah, so it simply is dylan being a troll again. nice.
